name: Scheduled Sign In Task

on:
  schedule:
    # 每天早上 8:00 (UTC+8) 运行
    - cron: '0 0 * * *'  # UTC 时间，对应北京时间早上8点
  workflow_dispatch:  # 允许手动触发

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run sign in script
      id: signin
      env:
        IKUUU_USERNAME: ${{ secrets.IKUUU_USERNAME }}
        IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
      run: |
        output=$(python scripts/signin.py)
        echo "$output"
        if ! echo "$output" | grep -q "Checkin successful"; then
          echo "::error::Sign in failed"
          exit 1
        fi

    - name: Send notification on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '签到失败通知',
            body: `签到任务在 ${new Date().toISOString()} 执行失败。\n\n可能需要更新 session，请检查工作流程日志了解详细信息。\n\n[查看运行日志](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
          });
